# Generated by Django 4.2.11 on 2024-04-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=100)),
                ('mahsulot_izohi', models.CharField(max_length=200)),
                ('rasm', models.ImageField(blank=True, upload_to='')),
                ('mahsulot_narxi', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
